server:
  port: 8888

spring:
  application:
    name: myblog-api
  mvc:
    servlet:
      path: /api
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://124.221.170.69:3306/myblog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root4737515
  # 腾讯应用服务器Redis
  redis:
    host: 124.221.170.69
    port: 6379
    password: root@4737515
  # 上传文件总的最大值
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 2MB

mybatis-plus:
  configuration:
    # 在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id

# 七牛云密钥
qiniu:
  accessKey: BOVQjrlVbKlpBiSt7NamRxT4dOaBfphZvs57Ljlg
  secretKey: GE6AugwKWk4ITbVvSkgWMnlJwiaZIQcKy6p-LhYB